alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'
alias ls='ls -G'
alias ll='ls -alF'
alias grep='grep --color=auto'
alias pingg='ping 8.8.8.8'
alias pacman='pacman --color=auto'
alias vi='vim'
alias index='(ctags -R --sort=foldcase .; mkid)'
